#!/bin/zsh

export ZSH="${XDG_HOME:-HOME}/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~{XDG_HOME}/.p10k.zsh.
[[ ! -f ${XDG_HOME}/.p10k.zsh ]] || source ${XDG_HOME}/.p10k.zsh
