#!/bin/env bash
if [[ "${BASH_SOURCE[0]}" -ef "$0" ]] || [[ $ZSH_EVAL_CONTEXT == toplevel ]];
then
    echo "This file is meant to be sourced."
    exit 1
fi

function prepend_to_path {
    PATH_ENTRY="$1"
    PATH="${PATH_ENTRY:+$PATH_ENTRY:}$PATH"
}

function append_to_path {
    PATH_ENTRY="$1"
    PATH="$PATH${PATH_ENTRY:+:$PATH_ENTRY}"
}

. "${XDG_CONFIG_HOME:-$HOME/.config}/bash/defaults"

HOME_DIR="${XDG_HOME:-$HOME}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"

. "${CONFIG_DIR}/zsh/oh-my-zsh"

# Set aliases last to override oh-my-zsh defaults
. "${CONFIG_DIR}/bash/aliases"

prepend_to_path "${HOME_DIR}/bin"

export PATH
