#!/bin/env bash
if [[ "${BASH_SOURCE[0]}" -ef "$0" ]] || [[ $ZSH_EVAL_CONTEXT == toplevel ]];
then
    echo "This file is meant to be sourced."
    exit 1
fi

##### Editors #####

alias v="nvim"
alias vi="nvim"

##### Git #####

git_top_level() {
    TOP_LEVEL=$(git rev-parse --show-toplevel) || return
    if [ -d "$TOP_LEVEL" ]; then
        cd "$TOP_LEVEL" || return
    fi
}
alias gcd=git_top_level

##### Multiplexers #####

alias t="tmux"
alias ta="tmux attach"

##### Python #####

alias pip="python3 -m pip"
alias pip3="pip"

# add pyenv shim to path
if command -v pyenv 1>/dev/null 2>&1; then
     eval "$(pyenv init -)"
fi

##### Java #####

select_java_version() {
	version=$1
    	JAVA_HOME=$(/usr/libexec/java_home -v"$version");
        export JAVA_HOME
    	java -version
}
alias jdk="select_java_version"


##### Shell Utils #####

if where eza &> /dev/null; then
    eza_lst() {
        TREE_DEPTH="3"
        if [[ $1 =~ ^[0-9]+$ ]]; then
            TREE_DEPTH=$1
            shift
        fi

        exa --tree --all --level "$TREE_DEPTH" "$@"
    }

    export EZA_COLORS="gm=33:ga=31"

    alias l="eza"
    alias ll="eza --header --all --long --git --color=always --icons=auto"
    alias lt="eza_lst"
fi

##### Custom #####

# shellcheck disable=SC2139 # I actually do want expand on define
alias config="$XDG_CONFIG_HOME"

alias c="clear"

function man(){
	MAN="/usr/bin/man"
	MANPATHS=("/usr/share/man" "/usr/local/share/man" "/nix/var/nix/profiles/default/share/man" "$XDG_HOME/.nix-profile/share/man")
	if [ -n "$1" ]; then
		$MAN "$@"
		return $?
	else
		fd -tf -tl . "${MANPATHS[@]}" | sed "s|.*\/||" | sed "s|\..*||" | fzf --reverse --preview="$MAN {}" | xargs $MAN
		return $?
	fi
}
