#!/bin/bash

##### Editors #####

alias v="nvim"
alias vi="nvim"

##### Multiplexers #####

alias t="tmux"
alias ta="tmux attach"

##### Python #####

alias pip="python3 -m pip"
alias pip3="pip"

##### Shell Utils #####

# exa - https://the.exa.website/
if where exa &> /dev/null; then
    function exa_lst {
        TREE_DEPTH="3"
        if [[ $1 =~ ^[0-9]+$ ]]; then
            TREE_DEPTH=$1
            shift
        fi

        exa --tree --all --level "$TREE_DEPTH" "$@"
    }

    alias ls="exa --header --all"
    alias lsa="exa --header --all --long --git"
    alias lst="exa_lst"
fi

##### Custom #####

alias config="$XDG_CONFIG_HOME"
