#!/bin/bash

##### Editors #####

alias v="nvim"
alias vi="nvim"

##### Multiplexers #####

alias t="tmux"
alias ta="tmux attach"

##### Python #####

alias pip="python3 -m pip"
alias pip3="pip"

# add pyenv shim to path
if command -v pyenv 1>/dev/null 2>&1; then
     eval "$(pyenv init -)"
fi

##### Java #####

select_java_version() {
	version=$1
    	JAVA_HOME=$(/usr/libexec/java_home -v"$version");
        export JAVA_HOME
    	java -version
}
alias jdk="select_java_version"


##### Shell Utils #####

# exa - https://the.exa.website/
if where exa &> /dev/null; then
    function exa_lst {
        TREE_DEPTH="3"
        if [[ $1 =~ ^[0-9]+$ ]]; then
            TREE_DEPTH=$1
            shift
        fi

        exa --tree --all --level "$TREE_DEPTH" "$@"
    }

    alias l="exa"
    alias ll="exa --header --all --long --git"
    alias lt="exa_lst"
fi

##### Custom #####

# shellcheck disable=SC2139 # I actually do want expand on define
alias config="$XDG_CONFIG_HOME"
