#!/bin/env bash
if [[ "${BASH_SOURCE[0]}" -ef "$0" ]] || [[ $ZSH_EVAL_CONTEXT == toplevel ]];
then
    echo "This file is meant to be sourced."
    exit 1
fi

# Make VIM the default editor
export VISUAL=nvim
export EDITOR="${VISUAL}"

# Set XDG Based Directories
export XDG_HOME="${HOME}"
export XDG_CACHE_HOME="${XDG_HOME}/.cache"
export XDG_CONFIG_HOME="${XDG_HOME}/.config"
export XDG_STATE_HOME="${XDG_HOME}/.local/state"
export XDG_CACHE_HOME="${XDG_HOME}/.cache"
export XDG_DATA_HOME="${XDG_HOME}/.local/share"

# Set other app directories
export IPYTHONDIR=${XDG_CONFIG_HOME:-$HOME/.config}/ipython
export JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/jupyter
