#!/bin/bash
if [[ "${BASH_SOURCE[0]}" -ef "$0" ]] || [[ $ZSH_EVAL_CONTEXT == toplevel ]];
then
    echo "This file is meant to be sourced."
    exit 1
fi

# Make VIM the default editor
export VISUAL=nvim
export EDITOR="${VISUAL}"

# Set XDG Based Directories
export XDG_HOME=~
export XDG_CACHE_HOME="${XDG_HOME}/.cache"
export XDG_CONFIG_HOME=~/.config
